name: MP-QQ CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build-qq-ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Dependencies
        run: npm install

      - name: Build
        uses: docker://qqminiapp/build:latest
        env:
          PLUGIN_VERSION: 1.0.0
          PLUGIN_DESC: CIè‡ªåŠ¨æ„å»ºä¸Šä¼ 
          PLUGIN_APPTOKEN: ${{ secrets.QQ_UPLOAD_TOKEN }}
          PLUGIN_BUILDUSER: ${{ github.actor }}
          PLUGIN_EXPERIENCE: true
        run: npm run build:mp-weixin

  ding-notice:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - name: PR_INFO
        run: |
          echo PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }') >> $GITHUB_ENV
          echo PR_TITLE=$(jq --raw-output .pull_request.title "$GITHUB_EVENT_PATH") >> $GITHUB_ENV
          echo PR_URL=$(jq --raw-output .pull_request._links.html.href "$GITHUB_EVENT_PATH") >> $GITHUB_ENV
          echo PR_USER=$(jq --raw-output .pull_request.user.login "$GITHUB_EVENT_PATH") >> $GITHUB_ENV

      - name: Ding-Notice
        if: ${{ success() }}
        uses: fifsky/dingtalk-action@master
        with:
          url: ${{ secrets.DINGTALK_WEBHOOK }}
          type: markdown
          content: |
            # ğŸ‘¨â€ğŸ’» QQå°ç¨‹åº: æ„å»º&å‘å¸ƒæˆåŠŸ ğŸ‰ğŸ‰ğŸ‰
            > Build of [# ${{ env.PR_TITLE }}](${{ env.PR_URL }}) by ${{ env.PR_USER }} success
            > ^_^ from github action message

# å‚è€ƒ
# 1. https://segmentfault.com/a/1190000039125224
