name: MP-QQ CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build-qq-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Node ENV
        uses: actions/setup-node@master
        with:
          node-version: 14.15.0

      - name: Install Dependencies
        run: npm install

      - name: Set env
        run: echo "VUE_APP_V1_API_HTTP_URL=$V1_API_RELEASE_HTTP_URL/http/v1/" >> .env

      - name: PreBuild
        run: npm run build:mp-qq

      - name: Build
        uses: docker://qqminiapp/build:latest
        env:
          PLUGIN_VERSION: 1.0.0
          PLUGIN_DESC: CIè‡ªåŠ¨æ„å»ºä¸Šä¼ 
          PLUGIN_APPTOKEN: ${{ secrets.QQ_UPLOAD_TOKEN }}
          PLUGIN_BUILDUSER: ${{ github.actor }}
          PLUGIN_EXPERIENCE: true
          PLUGIN_SOURCECODEPATH: ./dist/build/mp-qq

  ding-notice:
    needs: build-qq-ci
    runs-on: ubuntu-latest

    steps:
      - name: Ding-Notice
        if: ${{ success() }}
        uses: fifsky/dingtalk-action@master
        with:
          url: ${{ secrets.DINGTALK_WEBHOOK }}
          type: markdown
          content: |
            # ğŸ‘¨â€ğŸ’» [mp-ci]QQå°ç¨‹åº: æ„å»º&å‘å¸ƒæˆåŠŸ ğŸ‰ğŸ‰ğŸ‰
            > Build of sword-app success
            > ^_^ from github action message

# å‚è€ƒ
# 1. https://segmentfault.com/a/1190000039125224
