name: MP-WEIXIN CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-weixin-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Node ENV
        uses: actions/setup-node@master
        with:
          node-version: 14.15.0

      - name: Install Dependencies
        run: npm i

      - name: Set env
        run: echo "VUE_APP_V1_API_HTTP_URL=$V1_API_RELEASE_HTTP_URL/http/v1/" >> .env

      - name: Build
        run: npm run build:mp-weixin

      # see Project/Settings/Secrets
      - name: Generate private key for upload
        run: echo "$UPLOAD_PRIVATE_KEY" > private.key
        env:
          UPLOAD_PRIVATE_KEY: ${{ secrets.WEIXIN_UPLOAD_PRIVATE_KEY }}

      - name: Set PackageJson
        run: cp ./package.json ./dist/build/mp-weixin/package.json

      # ä¸Šä¼ ä»£ç 
      - name: Upload to WeChat
        run: npx mp-ci upload ./dist/build/mp-weixin --pkp=./private.key

  ding-notice:
    needs: build-weixin-ci
    runs-on: ubuntu-latest

    steps:
      - name: Version
        id: version
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: ./package.json
          property: version

      - name: Ding-Notice
        if: ${{ success() }}
        uses: fifsky/dingtalk-action@master
        with:
          url: ${{ secrets.DINGTALK_WEBHOOK }}
          type: markdown
          content: |
            # ğŸ‘¨â€ğŸ’» [mp-ci]å¾®ä¿¡å°ç¨‹åº: æ„å»º&å‘å¸ƒæˆåŠŸ ğŸ‰ğŸ‰ğŸ‰
            ç‰ˆæœ¬å·: ${{steps.version.outputs.value}}
            > Build of sword-app success
            > ^_^ from github action message

# å‚è€ƒ
# 1. https://segmentfault.com/a/1190000039125224
