name: MP-WEIXIN CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-weixin-ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm i

      - name: Build
        run: npm run build:mp-weixin

      # see Project/Settings/Secrets
      - name: Generate private key for upload
        run: echo "$WEIXIN_UPLOAD_PRIVATE_KEY" > private.key
        env:
          UPLOAD_PRIVATE_KEY: ${{ secrets.WEIXIN_UPLOAD_PRIVATE_KEY }}
      # ä¸Šä¼ ä»£ç 
      - name: Upload to WeChat
        run: npx mp-ci upload ./ --pkp=./private.key --no-test

  ding-notice:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - name: PR_INFO
        run: |
          echo PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }') >> $GITHUB_ENV
          echo PR_TITLE=$(jq --raw-output .pull_request.title "$GITHUB_EVENT_PATH") >> $GITHUB_ENV
          echo PR_URL=$(jq --raw-output .pull_request._links.html.href "$GITHUB_EVENT_PATH") >> $GITHUB_ENV
          echo PR_USER=$(jq --raw-output .pull_request.user.login "$GITHUB_EVENT_PATH") >> $GITHUB_ENV

      - name: Ding-Notice
        if: ${{ success() }}
        uses: fifsky/dingtalk-action@master
        with:
          url: ${{ secrets.DINGTALK_WEBHOOK }}
          type: markdown
          content: |
            # ğŸ‘¨â€ğŸ’» å¾®ä¿¡å°ç¨‹åº: æ„å»º&å‘å¸ƒæˆåŠŸ ğŸ‰ğŸ‰ğŸ‰
            > Build of [# ${{ env.PR_TITLE }}](${{ env.PR_URL }}) by ${{ env.PR_USER }} success
            > ^_^ from github action message

# å‚è€ƒ
# 1. https://segmentfault.com/a/1190000039125224
